android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

android.suppressUnsupportedCompileSdk=35,34

# Configurações de assinatura para publicação na Play Store
RELEASE_STORE_FILE=../../plugpdv-release-key.jks
RELEASE_STORE_PASSWORD=0t0n1@Eb
RELEASE_KEY_ALIAS=plugpdv-alias
RELEASE_KEY_PASSWORD=0t0n1@Eb
